# Generated by Django 4.1.6 on 2023-02-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baqueros_caballos_florafauna'),
    ]

    operations = [
        migrations.AddField(
            model_name='baqueros',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caballos',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='florafauna',
            name='name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
