# Generated by Django 4.1.6 on 2023-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_baqueros_name_caballos_name_florafauna_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballos',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
